### PR TITLE
Plugin registry integration

### PR DESCRIPTION
**Pull request by buehlefs**
Integrate the new plugin registry.

- [x] Add registry service
- [x] Refactor settings page
    - [x] Refactor plugin/seed endpoints
    - [x] Refactor Service URL (LaTeX Renderer and Backend) discovery
    - [x] Add Services
    - [x] Add Env Variables
- [x] Refactor Plugin Lists (+new sidebar design)
- [ ] Refactor plugin chooser dialog
- [ ] Refactor Templates? <- later (depends on registry implementation of templates)

### CODE REVIEW

**Comment by krebsni** [comment]
Service url is not working if input for `addService()` includes trailing forward slash. Should be stripped in `setting-page.component.ts`.

**Comment by krebsni** [comment]
Once backend/latex renderer service are set, they cannot be changed. Perhaps include some kind of update/change feature (on setting-page).

**Comment by buehlefs** [comment]
> Service url is not working if input for addService() includes trailing forward slash. Should be stripped in setting-page.component.ts.

Won't fix. Two URLs that only differ in a final `/` at the end are different URLs and may result in different outputs. This means we cannot enforce one consistent style here. (See also <https://flask.palletsprojects.com/en/2.2.x/quickstart/#unique-urls-redirection-behavior>)

> Once backend/latex renderer service are set, they cannot be changed. Perhaps include some kind of update/change feature (on setting-page).

They can be changed. But you need to expand the full service list and select the services in that list.

**Comment by PhilWun** [comment]
We may need a new plugin type for plugins that load data like the Costume Loader plugin. After https://github.com/UST-QuAntiL/qhana-plugin-runner/pull/61 is merged it would show up under processing plugins which doesn't seem right. The new type would also need to be added to https://github.com/UST-QuAntiL/qhana-plugin-runner/blob/700d696392eb4ce6576d19e161149cf76f03af02/qhana_plugin_runner/api/plugin_schemas.py#L29

**Pull request merged**
